const CONTENT_BANK = [
  {
    contentKey: 'sleep_consistent_schedule',
    metricTags: ['sleep'],
    periodTags: ['day', 'week', 'month'],
    tone: 'actionable',
    text: 'Старайтесь ложиться и вставать примерно в одно и то же время, чтобы поддерживать более стабильный ритм сна.',
    sourceRef: 'Хелси_Сон.txt',
    status: 'approved',
    safetyFlags: ['allowed'],
    locale: 'ru',
  },
  {
    contentKey: 'sleep_reduce_evening_screens',
    metricTags: ['sleep', 'recovery'],
    periodTags: ['day', 'week'],
    tone: 'actionable',
    text: 'За час до сна приглушите свет и сократите яркие экраны, чтобы организму было легче переключиться на отдых.',
    sourceRef: 'Хелси_Сон.txt',
    status: 'approved',
    safetyFlags: ['allowed'],
    locale: 'ru',
  },
  {
    contentKey: 'sleep_bedroom_environment',
    metricTags: ['sleep'],
    periodTags: ['day', 'week', 'month'],
    tone: 'actionable',
    text: 'Прохладная, тихая и затемненная спальня часто помогает засыпать спокойнее и просыпаться мягче.',
    sourceRef: 'Хелси_Сон.txt',
    status: 'approved',
    safetyFlags: ['allowed'],
    locale: 'ru',
  },
  {
    contentKey: 'water_visible_bottle',
    metricTags: ['water'],
    periodTags: ['day', 'week'],
    tone: 'actionable',
    text: 'Держите воду на виду в течение дня: так проще вспоминать о небольших глотках между делами.',
    sourceRef: 'Хелси_вода.txt',
    status: 'approved',
    safetyFlags: ['allowed'],
    locale: 'ru',
  },
  {
    contentKey: 'water_regular_small_sips',
    metricTags: ['water', 'recovery'],
    periodTags: ['day', 'week', 'month'],
    tone: 'actionable',
    text: 'Пейте регулярно и небольшими порциями в течение дня, вместо того чтобы добирать весь объем за один раз.',
    sourceRef: 'Хелси_вода.txt',
    status: 'approved',
    safetyFlags: ['allowed'],
    locale: 'ru',
  },
  {
    contentKey: 'water_start_day_glass',
    metricTags: ['water'],
    periodTags: ['day'],
    tone: 'actionable',
    text: 'Начните день со стакана воды и добавьте еще несколько удобных точек для воды в течение дня.',
    sourceRef: 'Хелси_вода.txt',
    status: 'approved',
    safetyFlags: ['allowed'],
    locale: 'ru',
  },
  {
    contentKey: 'steps_short_walk_break',
    metricTags: ['steps', 'recovery'],
    periodTags: ['day', 'week'],
    tone: 'actionable',
    text: 'Короткая прогулка на 10–15 минут уже дает пользу и помогает разбить долгие периоды сидения.',
    sourceRef: 'Хелси - Шаги.txt',
    status: 'approved',
    safetyFlags: ['allowed'],
    locale: 'ru',
  },
  {
    contentKey: 'steps_move_regularly',
    metricTags: ['steps'],
    periodTags: ['week', 'month'],
    tone: 'actionable',
    text: 'Лучше набирать движение регулярно в течение недели, чем оставлять всю активность на один день.',
    sourceRef: 'Хелси - Шаги.txt',
    status: 'approved',
    safetyFlags: ['allowed'],
    locale: 'ru',
  },
  {
    contentKey: 'steps_reduce_sedentary_time',
    metricTags: ['steps', 'stress'],
    periodTags: ['day', 'week', 'month'],
    tone: 'actionable',
    text: 'Старайтесь прерывать долгие периоды сидения небольшим движением или сменой положения тела.',
    sourceRef: 'Хелси - Шаги.txt',
    status: 'approved',
    safetyFlags: ['allowed'],
    locale: 'ru',
  },
  {
    contentKey: 'stress_breathing_pause',
    metricTags: ['stress', 'recovery'],
    periodTags: ['day', 'week'],
    tone: 'actionable',
    text: 'Сделайте несколько медленных глубоких вдохов и выдохов: даже 3–5 минут помогают снизить напряжение.',
    sourceRef: 'Хелси_Стресс.txt',
    status: 'approved',
    safetyFlags: ['allowed'],
    locale: 'ru',
  },
  {
    contentKey: 'stress_focus_on_control',
    metricTags: ['stress'],
    periodTags: ['week', 'month'],
    tone: 'reflective',
    text: 'Если неделя была напряженной, попробуйте выделить то, на что вы реально можете повлиять, и начать с малого.',
    sourceRef: 'Хелси_Стресс.txt',
    status: 'approved',
    safetyFlags: ['allowed'],
    locale: 'ru',
  },
  {
    contentKey: 'stress_social_support',
    metricTags: ['stress', 'mood'],
    periodTags: ['week', 'month'],
    tone: 'supportive',
    text: 'Поддержка близких и короткий разговор с тем, кому вы доверяете, могут заметно снизить ощущение перегруза.',
    sourceRef: 'Хелси_Стресс.txt',
    status: 'approved',
    safetyFlags: ['allowed'],
    locale: 'ru',
  },
  {
    contentKey: 'energy_keep_regular_sleep',
    metricTags: ['energy', 'sleep'],
    periodTags: ['day', 'week', 'month'],
    tone: 'actionable',
    text: 'Для более ровной энергии полезно держать стабильный сон и не перегружать вечер лишними стимулами.',
    sourceRef: 'Хелси_Энергия.txt',
    status: 'approved',
    safetyFlags: ['allowed'],
    locale: 'ru',
  },
  {
    contentKey: 'energy_light_activity',
    metricTags: ['energy', 'steps'],
    periodTags: ['day', 'week'],
    tone: 'actionable',
    text: 'Умеренное движение днем часто помогает почувствовать больше бодрости и собранности.',
    sourceRef: 'Хелси_Энергия.txt',
    status: 'approved',
    safetyFlags: ['allowed'],
    locale: 'ru',
  },
  {
    contentKey: 'energy_plan_rest',
    metricTags: ['energy', 'recovery'],
    periodTags: ['week', 'month'],
    tone: 'supportive',
    text: 'Если энергии не хватает, попробуйте заранее оставлять в графике немного пространства для восстановления.',
    sourceRef: 'Хелси_Энергия.txt',
    status: 'approved',
    safetyFlags: ['allowed'],
    locale: 'ru',
  },
  {
    contentKey: 'mood_social_connection',
    metricTags: ['mood'],
    periodTags: ['day', 'week', 'month'],
    tone: 'supportive',
    text: 'Контакт с близкими, друзьями или коллегами может поддерживать настроение и давать ощущение опоры.',
    sourceRef: 'Хелси_настроения.txt',
    status: 'approved',
    safetyFlags: ['allowed'],
    locale: 'ru',
  },
  {
    contentKey: 'mood_physical_activity',
    metricTags: ['mood', 'steps', 'energy'],
    periodTags: ['day', 'week'],
    tone: 'actionable',
    text: 'Даже короткая физическая активность может мягко поддержать настроение и вернуть ощущение движения вперед.',
    sourceRef: 'Хелси_настроения.txt',
    status: 'approved',
    safetyFlags: ['allowed'],
    locale: 'ru',
  },
  {
    contentKey: 'mood_mindfulness_present',
    metricTags: ['mood', 'stress', 'recovery'],
    periodTags: ['day', 'week', 'month'],
    tone: 'reflective',
    text: 'Небольшая пауза с вниманием к дыханию, телу и текущему моменту может помочь снизить внутренний шум.',
    sourceRef: 'Хелси_настроения.txt',
    status: 'approved',
    safetyFlags: ['allowed'],
    locale: 'ru',
  },
  {
    contentKey: 'recovery_kind_to_self',
    metricTags: ['recovery', 'mood', 'stress'],
    periodTags: ['day', 'week', 'month'],
    tone: 'supportive',
    text: 'Относитесь к себе бережно: спокойные маленькие шаги обычно работают лучше, чем жесткие рывки.',
    sourceRef: 'Общий источник - Хелси.txt',
    status: 'approved',
    safetyFlags: ['allowed'],
    locale: 'ru',
  },
  {
    contentKey: 'positive_support_keep_going',
    metricTags: ['positive_support'],
    periodTags: ['day', 'week', 'month'],
    tone: 'supportive',
    text: 'Хорошая динамика уже видна. Сохраняйте этот ритм без лишнего давления на себя.',
    sourceRef: 'Общий источник - Хелси.txt',
    status: 'approved',
    safetyFlags: ['allowed'],
    locale: 'ru',
  },
  {
    contentKey: 'low_data_track_small_steps',
    metricTags: ['low_data'],
    periodTags: ['day', 'week', 'month'],
    tone: 'supportive',
    text: 'Даже короткие ежедневные отметки по сну, воде или настроению быстро делают картину понятнее.',
    sourceRef: 'Общий источник - Хелси.txt',
    status: 'approved',
    safetyFlags: ['allowed'],
    locale: 'ru',
  },
];

export function getHealthyContentBank() {
  return CONTENT_BANK;
}

