-- Шаблоны локаций офиса (блок / этаж / помещение) + начальное наполнение из legacy mobile

CREATE TABLE IF NOT EXISTS office_location_catalog (
    id SERIAL PRIMARY KEY,
    office_id INTEGER NOT NULL REFERENCES offices(id) ON DELETE CASCADE,
    block VARCHAR(255) NOT NULL DEFAULT '',
    floor_zone VARCHAR(255) NOT NULL DEFAULT '',
    room VARCHAR(255) NOT NULL DEFAULT '',
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_office_location_catalog_office_id ON office_location_catalog(office_id);
CREATE INDEX IF NOT EXISTS idx_office_location_catalog_office_active ON office_location_catalog(office_id, is_active);

-- Seed: office_id по совпадению offices.name с ключом из мобильного справочника
INSERT INTO office_location_catalog (office_id, block, floor_zone, room, sort_order, is_active)
SELECT o.id, v.block, v.floor_zone, v.room, v.sort_order, TRUE
FROM (
VALUES
    ('Teniz Towers', 'А', '1 этаж', 'Холл', 1),
    ('Teniz Towers', 'А', '1 этаж', 'Канцеллярия № А - 01 -18', 2),
    ('Teniz Towers', 'А', '1 этаж', 'Склад № А - 01 -17', 3),
    ('Teniz Towers', 'А', '1 этаж', 'Кабинет зав склада № А - 01 -16', 4),
    ('Teniz Towers', 'А', '1 этаж', 'Санузел Ж', 5),
    ('Teniz Towers', 'А', '1 этаж', 'Санузел М', 6),
    ('Teniz Towers', 'А', '1 этаж', 'Конф Зал "Толе би"', 7),
    ('Teniz Towers', 'А', '1 этаж', 'Конф Зал "А. Байтурсынов"', 8),
    ('Teniz Towers', 'А', '1 этаж', 'Конф Зал "А. Яссауи"', 9),
    ('Teniz Towers', 'А', '1 этаж', 'Лестница', 10),
    ('Teniz Towers', 'А', '2 этаж', 'Санузел Ж', 11),
    ('Teniz Towers', 'А', '2 этаж', 'Санузел М', 12),
    ('Teniz Towers', 'А', '2 этаж', 'Кухня № А - 02 -08', 13),
    ('Teniz Towers', 'А', '2 этаж', 'Конф Зал "Ы. Алтынсарин"', 14),
    ('Teniz Towers', 'А', '2 этаж', 'Конф Зал "Райымбек батыр"', 15),
    ('Teniz Towers', 'А', '2 этаж', 'Восточное крыло', 16),
    ('Teniz Towers', 'А', '2 этаж', 'Западное крыло', 17),
    ('Teniz Towers', 'А', '2 этаж', 'Кабинет директор комплайнс. № А - 02 -12', 18),
    ('Teniz Towers', 'А', '2 этаж', 'Лестница', 19),
    ('Teniz Towers', 'А', '3 этаж', 'Санузел Ж', 20),
    ('Teniz Towers', 'А', '3 этаж', 'Санузел М', 21),
    ('Teniz Towers', 'А', '3 этаж', 'Восточное крыло Опен спейс', 22),
    ('Teniz Towers', 'А', '3 этаж', 'Кухня № А - 03 -08', 23),
    ('Teniz Towers', 'А', '3 этаж', 'Кабинет HR Директора № А - 03 -09', 24),
    ('Teniz Towers', 'А', '3 этаж', 'Западное крыло', 25),
    ('Teniz Towers', 'А', '3 этаж', 'Конф Зал "Керей ЖӘнІбек"', 26),
    ('Teniz Towers', 'А', '3 этаж', 'Лестница', 27),
    ('Teniz Towers', 'А', '4 этаж', '', 28),
    ('Teniz Towers', 'А', 'Лифт 1', '', 29),
    ('Teniz Towers', 'А', 'Лифт 2', '', 30),
    ('Teniz Towers', 'Б', '1 этаж', 'Фуд корт', 31),
    ('Teniz Towers', 'Б', '1 этаж', 'Кабинет  под склад IT № Б - 01 -03', 32),
    ('Teniz Towers', 'Б', '1 этаж', 'Архив № Б - 01 -04', 33),
    ('Teniz Towers', 'Б', '1 этаж', 'Кабинет отдел продаж № Б - 01 -05', 34),
    ('Teniz Towers', 'Б', '1 этаж', 'Кабинет № Б - 01 -06', 35),
    ('Teniz Towers', 'Б', '1 этаж', 'Помещение АО', 36),
    ('Teniz Towers', 'Б', '1 этаж', 'Столовая', 37),
    ('Teniz Towers', 'Б', '1 этаж', 'Медкабинет', 38),
    ('Teniz Towers', 'Б', '1 этаж', 'Санузел Ж', 39),
    ('Teniz Towers', 'Б', '1 этаж', 'Санузел М', 40),
    ('Teniz Towers', 'Б', '2 этаж', 'НОК', 41),
    ('Teniz Towers', 'Б', '2 этаж', 'Конференц зал "Абылай хан"', 42),
    ('Teniz Towers', 'Б', '2 этаж', 'Кофкпоинт', 43),
    ('Teniz Towers', 'Б', '2 этаж', 'Санузел Ж', 44),
    ('Teniz Towers', 'Б', '2 этаж', 'Санузел М', 45),
    ('Teniz Towers', 'Б', '2 этаж', 'Кабинет Корпсекретаря № Б - 02 -03', 46),
    ('Teniz Towers', 'Б', '3 этаж', '', 47),
    ('Teniz Towers', 'Б', '4 этаж', 'Склад техический отдел № Б - 03 -18', 48),
    ('Teniz Towers', 'Б', '4 этаж', 'Кухня СЕО № Б - 03 -18', 49),
    ('Teniz Towers', 'Б', '4 этаж', 'Кабинет обучения. Конференц зал "Абай"', 50),
    ('Teniz Towers', 'Б', '4 этаж', 'Кабинет CEO', 51),
    ('Teniz Towers', 'Б', '4 этаж', 'Кабинет Техдиректора', 52),
    ('Teniz Towers', 'Б', '4 этаж', 'Конф Зал "МолдаҒулова"', 53),
    ('Teniz Towers', 'Б', '4 этаж', 'Конф Зал "Әйтеке би"', 54),
    ('Teniz Towers', 'Б', '4 этаж', 'Кабинет СВА, Аудиторы внутренние', 55),
    ('Teniz Towers', 'Б', '4 этаж', 'Кабинет', 56),
    ('Teniz Towers', 'Б', '4 этаж', 'Опен спейс', 57),
    ('Teniz Towers', 'Б', '4 этаж', 'Санузел Ж', 58),
    ('Teniz Towers', 'Б', '4 этаж', 'Санузел М', 59),
    ('Teniz Towers', 'Б', '4 этаж', 'Конф Зал (ПРАВЛЕНИЕ) "Жамбыл"', 60),
    ('Teniz Towers', 'Б', '4 этаж', 'Конф Зал (чернозал) "Қазыбек би"', 61),
    ('Teniz Towers', 'В', '1 этаж', 'Холл', 62),
    ('Teniz Towers', 'В', '1 этаж', 'ДЦЗ', 63),
    ('Teniz Towers', 'В', '1 этаж', 'Лестница', 64),
    ('Teniz Towers', 'В', '2 этаж', 'ТД (Трансмисся)', 65),
    ('Teniz Towers', 'В', '2 этаж', 'кабинет № Б - 02 -02', 66),
    ('Teniz Towers', 'В', '2 этаж', 'Лифтовой холл', 67),
    ('Teniz Towers', 'В', '2 этаж', 'Конф Зал (Трансмисся)', 68),
    ('Teniz Towers', 'В', '3 этаж', 'Департамент IT безопасность', 69),
    ('Teniz Towers', 'В', '3 этаж', 'Кухня', 70),
    ('Teniz Towers', 'В', '3 этаж', 'Лифтовой холл', 71),
    ('Teniz Towers', 'В', '3 этаж', 'кабинет № Б - 03 -07', 72),
    ('Teniz Towers', 'В', '4 этаж', 'Лифтовой холл', 73),
    ('Teniz Towers', 'В', '4 этаж', 'Опенспейс', 74),
    ('Teniz Towers', 'В', '4 этаж', 'Конф Зал № Б - 04 -08', 75),
    ('Teniz Towers', 'В', '4 этаж', 'Кабинет Специалист по рискам № Б - 04 -06', 76),
    ('Teniz Towers', 'В', '4 этаж', 'Кофепоинт', 77),
    ('Teniz Towers', 'В', 'лифт', '', 78),
    ('Teniz Towers', 'Г', '1 этаж', '', 79),
    ('Teniz Towers', 'Г', '2 этаж', '', 80),
    ('Teniz Towers', 'Г', '3 этаж', '', 81),
    ('Teniz Towers', 'Г', '4 этаж', '', 82),
    ('Teniz Towers', 'Г', 'Лестница', '', 83),
    ('Nurlytau', 'Н', '', '', 84),
    ('Koktem Tower', 'К', '', '', 85),
    ('Venus', 'В', '', '', 86),
    ('Koktem Grand', 'К', '', '', 87)
) AS v(office_name, block, floor_zone, room, sort_order)
JOIN offices o ON o.name = v.office_name;
